package com.produce.dao;

import com.produce.dao.sqlProvider.TBillSqlProvider;
import com.produce.entity.TBill;
import com.produce.entity.TBillCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @SelectProvider(type= TBillSqlProvider.class, method="countByExample")
    long countByExample(TBillCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TBillSqlProvider.class, method="deleteByExample")
    int deleteByExample(TBillCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_bill",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_bill (id, order_id, ",
        "body, pay_type, fee, ",
        "car_owner_id, car_plate, ",
        "company_id, park_id, ",
        "time_start, create_time, ",
        "update_time, flag, ",
        "trading_status)",
        "values (#{id,jdbcType=INTEGER}, #{orderId,jdbcType=INTEGER}, ",
        "#{body,jdbcType=VARCHAR}, #{payType,jdbcType=INTEGER}, #{fee,jdbcType=INTEGER}, ",
        "#{carOwnerId,jdbcType=INTEGER}, #{carPlate,jdbcType=VARCHAR}, ",
        "#{companyId,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{timeStart,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR}, #{flag,jdbcType=INTEGER}, ",
        "#{tradingStatus,jdbcType=VARCHAR})"
    })
    int insert(TBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @InsertProvider(type=TBillSqlProvider.class, method="insertSelective")
    int insertSelective(TBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @SelectProvider(type=TBillSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="body", property="body", jdbcType=JdbcType.VARCHAR),
        @Result(column="pay_type", property="payType", jdbcType=JdbcType.INTEGER),
        @Result(column="fee", property="fee", jdbcType=JdbcType.INTEGER),
        @Result(column="car_owner_id", property="carOwnerId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="time_start", property="timeStart", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="flag", property="flag", jdbcType=JdbcType.INTEGER),
        @Result(column="trading_status", property="tradingStatus", jdbcType=JdbcType.VARCHAR)
    })
    List<TBill> selectByExample(TBillCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, order_id, body, pay_type, fee, car_owner_id, car_plate, company_id, park_id, ",
        "time_start, create_time, update_time, flag, trading_status",
        "from t_bill",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="body", property="body", jdbcType=JdbcType.VARCHAR),
        @Result(column="pay_type", property="payType", jdbcType=JdbcType.INTEGER),
        @Result(column="fee", property="fee", jdbcType=JdbcType.INTEGER),
        @Result(column="car_owner_id", property="carOwnerId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="time_start", property="timeStart", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="flag", property="flag", jdbcType=JdbcType.INTEGER),
        @Result(column="trading_status", property="tradingStatus", jdbcType=JdbcType.VARCHAR)
    })
    TBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TBillSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TBill record, @Param("example") TBillCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TBillSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TBill record, @Param("example") TBillCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TBillSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill
     *
     * @mbg.generated
     */
    @Update({
        "update t_bill",
        "set order_id = #{orderId,jdbcType=INTEGER},",
          "body = #{body,jdbcType=VARCHAR},",
          "pay_type = #{payType,jdbcType=INTEGER},",
          "fee = #{fee,jdbcType=INTEGER},",
          "car_owner_id = #{carOwnerId,jdbcType=INTEGER},",
          "car_plate = #{carPlate,jdbcType=VARCHAR},",
          "company_id = #{companyId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "time_start = #{timeStart,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "flag = #{flag,jdbcType=INTEGER},",
          "trading_status = #{tradingStatus,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TBill record);
}