package com.produce.dao;

import com.produce.dao.sqlProvider.TNoticeSqlProvider;
import com.produce.entity.TNotice;
import com.produce.entity.TNoticeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @SelectProvider(type= TNoticeSqlProvider.class, method="countByExample")
    long countByExample(TNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TNoticeSqlProvider.class, method="deleteByExample")
    int deleteByExample(TNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_notice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_notice (id, n_area, ",
        "n_type, begin_time, ",
        "end_time, n_content, ",
        "n_link, status, create_person, ",
        "create_time)",
        "values (#{id,jdbcType=INTEGER}, #{nArea,jdbcType=VARCHAR}, ",
        "#{nType,jdbcType=INTEGER}, #{beginTime,jdbcType=VARCHAR}, ",
        "#{endTime,jdbcType=VARCHAR}, #{nContent,jdbcType=VARCHAR}, ",
        "#{nLink,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, #{createPerson,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=VARCHAR})"
    })
    int insert(TNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @InsertProvider(type=TNoticeSqlProvider.class, method="insertSelective")
    int insertSelective(TNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @SelectProvider(type=TNoticeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="n_area", property="nArea", jdbcType=JdbcType.VARCHAR),
        @Result(column="n_type", property="nType", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="n_content", property="nContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="n_link", property="nLink", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_person", property="createPerson", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR)
    })
    List<TNotice> selectByExample(TNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, n_area, n_type, begin_time, end_time, n_content, n_link, status, create_person, ",
        "create_time",
        "from t_notice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="n_area", property="nArea", jdbcType=JdbcType.VARCHAR),
        @Result(column="n_type", property="nType", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="n_content", property="nContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="n_link", property="nLink", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_person", property="createPerson", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR)
    })
    TNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TNoticeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TNotice record, @Param("example") TNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TNoticeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TNotice record, @Param("example") TNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TNoticeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated
     */
    @Update({
        "update t_notice",
        "set n_area = #{nArea,jdbcType=VARCHAR},",
          "n_type = #{nType,jdbcType=INTEGER},",
          "begin_time = #{beginTime,jdbcType=VARCHAR},",
          "end_time = #{endTime,jdbcType=VARCHAR},",
          "n_content = #{nContent,jdbcType=VARCHAR},",
          "n_link = #{nLink,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_person = #{createPerson,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TNotice record);
}