package com.produce.dao;

import com.produce.dao.sqlProvider.TParkCarSqlProvider;
import com.produce.entity.TParkCar;
import com.produce.entity.TParkCarCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TParkCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @SelectProvider(type= TParkCarSqlProvider.class, method="countByExample")
    long countByExample(TParkCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TParkCarSqlProvider.class, method="deleteByExample")
    int deleteByExample(TParkCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_park_car",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_park_car (id, car_plate, ",
        "car_owner_id, park_id, ",
        "begin_date, end_date, ",
        "parking_space, is_enable, ",
        "update_time)",
        "values (#{id,jdbcType=INTEGER}, #{carPlate,jdbcType=VARCHAR}, ",
        "#{carOwnerId,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{beginDate,jdbcType=VARCHAR}, #{endDate,jdbcType=VARCHAR}, ",
        "#{parkingSpace,jdbcType=INTEGER}, #{isEnable,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=VARCHAR})"
    })
    int insert(TParkCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @InsertProvider(type=TParkCarSqlProvider.class, method="insertSelective")
    int insertSelective(TParkCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @SelectProvider(type=TParkCarSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_owner_id", property="carOwnerId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_date", property="beginDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="parking_space", property="parkingSpace", jdbcType=JdbcType.INTEGER),
        @Result(column="is_enable", property="isEnable", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    List<TParkCar> selectByExample(TParkCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, car_plate, car_owner_id, park_id, begin_date, end_date, parking_space, is_enable, ",
        "update_time",
        "from t_park_car",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_owner_id", property="carOwnerId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="begin_date", property="beginDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_date", property="endDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="parking_space", property="parkingSpace", jdbcType=JdbcType.INTEGER),
        @Result(column="is_enable", property="isEnable", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    TParkCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TParkCarSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TParkCar record, @Param("example") TParkCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TParkCarSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TParkCar record, @Param("example") TParkCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TParkCarSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TParkCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_car
     *
     * @mbg.generated
     */
    @Update({
        "update t_park_car",
        "set car_plate = #{carPlate,jdbcType=VARCHAR},",
          "car_owner_id = #{carOwnerId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "begin_date = #{beginDate,jdbcType=VARCHAR},",
          "end_date = #{endDate,jdbcType=VARCHAR},",
          "parking_space = #{parkingSpace,jdbcType=INTEGER},",
          "is_enable = #{isEnable,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TParkCar record);
}