package com.produce.dao;

import com.produce.dao.sqlProvider.TPaySequenceSqlProvider;
import com.produce.entity.TPaySequence;
import com.produce.entity.TPaySequenceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TPaySequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @SelectProvider(type= TPaySequenceSqlProvider.class, method="countByExample")
    long countByExample(TPaySequenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TPaySequenceSqlProvider.class, method="deleteByExample")
    int deleteByExample(TPaySequenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_pay_sequence",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_pay_sequence (id, car_owner_id, ",
        "pay_type_id, sequence)",
        "values (#{id,jdbcType=INTEGER}, #{carOwnerId,jdbcType=INTEGER}, ",
        "#{payTypeId,jdbcType=INTEGER}, #{sequence,jdbcType=INTEGER})"
    })
    int insert(TPaySequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @InsertProvider(type=TPaySequenceSqlProvider.class, method="insertSelective")
    int insertSelective(TPaySequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @SelectProvider(type=TPaySequenceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="car_owner_id", property="carOwnerId", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_type_id", property="payTypeId", jdbcType=JdbcType.INTEGER),
        @Result(column="sequence", property="sequence", jdbcType=JdbcType.INTEGER)
    })
    List<TPaySequence> selectByExample(TPaySequenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, car_owner_id, pay_type_id, sequence",
        "from t_pay_sequence",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="car_owner_id", property="carOwnerId", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_type_id", property="payTypeId", jdbcType=JdbcType.INTEGER),
        @Result(column="sequence", property="sequence", jdbcType=JdbcType.INTEGER)
    })
    TPaySequence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPaySequenceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TPaySequence record, @Param("example") TPaySequenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPaySequenceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TPaySequence record, @Param("example") TPaySequenceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPaySequenceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TPaySequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_sequence
     *
     * @mbg.generated
     */
    @Update({
        "update t_pay_sequence",
        "set car_owner_id = #{carOwnerId,jdbcType=INTEGER},",
          "pay_type_id = #{payTypeId,jdbcType=INTEGER},",
          "sequence = #{sequence,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPaySequence record);
}