package com.produce.entity;

public class TCarOwner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_owner.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_owner.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_owner.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_owner.phoneNumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_owner.city
     *
     * @mbg.generated
     */
    private Integer city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_owner.notice_ids
     *
     * @mbg.generated
     */
    private String noticeIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_owner.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_owner.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_owner.id
     *
     * @return the value of t_car_owner.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_owner.id
     *
     * @param id the value for t_car_owner.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_owner.name
     *
     * @return the value of t_car_owner.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_owner.name
     *
     * @param name the value for t_car_owner.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_owner.sex
     *
     * @return the value of t_car_owner.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_owner.sex
     *
     * @param sex the value for t_car_owner.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_owner.phoneNumber
     *
     * @return the value of t_car_owner.phoneNumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_owner.phoneNumber
     *
     * @param phonenumber the value for t_car_owner.phoneNumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_owner.city
     *
     * @return the value of t_car_owner.city
     *
     * @mbg.generated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_owner.city
     *
     * @param city the value for t_car_owner.city
     *
     * @mbg.generated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_owner.notice_ids
     *
     * @return the value of t_car_owner.notice_ids
     *
     * @mbg.generated
     */
    public String getNoticeIds() {
        return noticeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_owner.notice_ids
     *
     * @param noticeIds the value for t_car_owner.notice_ids
     *
     * @mbg.generated
     */
    public void setNoticeIds(String noticeIds) {
        this.noticeIds = noticeIds == null ? null : noticeIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_owner.update_time
     *
     * @return the value of t_car_owner.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_owner.update_time
     *
     * @param updateTime the value for t_car_owner.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_owner.create_time
     *
     * @return the value of t_car_owner.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_owner.create_time
     *
     * @param createTime the value for t_car_owner.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}