package com.produce.entity;

public class TCardSequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_sequence.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_sequence.car_owner_id
     *
     * @mbg.generated
     */
    private Integer carOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_sequence.card_id
     *
     * @mbg.generated
     */
    private Integer cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_sequence.sequence
     *
     * @mbg.generated
     */
    private Integer sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_sequence.id
     *
     * @return the value of t_card_sequence.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_sequence.id
     *
     * @param id the value for t_card_sequence.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_sequence.car_owner_id
     *
     * @return the value of t_card_sequence.car_owner_id
     *
     * @mbg.generated
     */
    public Integer getCarOwnerId() {
        return carOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_sequence.car_owner_id
     *
     * @param carOwnerId the value for t_card_sequence.car_owner_id
     *
     * @mbg.generated
     */
    public void setCarOwnerId(Integer carOwnerId) {
        this.carOwnerId = carOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_sequence.card_id
     *
     * @return the value of t_card_sequence.card_id
     *
     * @mbg.generated
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_sequence.card_id
     *
     * @param cardId the value for t_card_sequence.card_id
     *
     * @mbg.generated
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_sequence.sequence
     *
     * @return the value of t_card_sequence.sequence
     *
     * @mbg.generated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_sequence.sequence
     *
     * @param sequence the value for t_card_sequence.sequence
     *
     * @mbg.generated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}