package com.produce.entity;

public class TCardCoupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.card_coupon_name
     *
     * @mbg.generated
     */
    private String cardCouponName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.card_coupon_type
     *
     * @mbg.generated
     */
    private Integer cardCouponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.begin_time
     *
     * @mbg.generated
     */
    private String beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.end_time
     *
     * @mbg.generated
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.card_ issuer
     *
     * @mbg.generated
     */
    private String cardIssuer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.car_plate
     *
     * @mbg.generated
     */
    private String carPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card_coupon.car_owner_id
     *
     * @mbg.generated
     */
    private Integer carOwnerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.id
     *
     * @return the value of t_card_coupon.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.id
     *
     * @param id the value for t_card_coupon.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.card_coupon_name
     *
     * @return the value of t_card_coupon.card_coupon_name
     *
     * @mbg.generated
     */
    public String getCardCouponName() {
        return cardCouponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.card_coupon_name
     *
     * @param cardCouponName the value for t_card_coupon.card_coupon_name
     *
     * @mbg.generated
     */
    public void setCardCouponName(String cardCouponName) {
        this.cardCouponName = cardCouponName == null ? null : cardCouponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.card_coupon_type
     *
     * @return the value of t_card_coupon.card_coupon_type
     *
     * @mbg.generated
     */
    public Integer getCardCouponType() {
        return cardCouponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.card_coupon_type
     *
     * @param cardCouponType the value for t_card_coupon.card_coupon_type
     *
     * @mbg.generated
     */
    public void setCardCouponType(Integer cardCouponType) {
        this.cardCouponType = cardCouponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.begin_time
     *
     * @return the value of t_card_coupon.begin_time
     *
     * @mbg.generated
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.begin_time
     *
     * @param beginTime the value for t_card_coupon.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime == null ? null : beginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.end_time
     *
     * @return the value of t_card_coupon.end_time
     *
     * @mbg.generated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.end_time
     *
     * @param endTime the value for t_card_coupon.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.card_ issuer
     *
     * @return the value of t_card_coupon.card_ issuer
     *
     * @mbg.generated
     */
    public String getCardIssuer() {
        return cardIssuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.card_ issuer
     *
     * @param cardIssuer the value for t_card_coupon.card_ issuer
     *
     * @mbg.generated
     */
    public void setCardIssuer(String cardIssuer) {
        this.cardIssuer = cardIssuer == null ? null : cardIssuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.car_plate
     *
     * @return the value of t_card_coupon.car_plate
     *
     * @mbg.generated
     */
    public String getCarPlate() {
        return carPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.car_plate
     *
     * @param carPlate the value for t_card_coupon.car_plate
     *
     * @mbg.generated
     */
    public void setCarPlate(String carPlate) {
        this.carPlate = carPlate == null ? null : carPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.park_id
     *
     * @return the value of t_card_coupon.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.park_id
     *
     * @param parkId the value for t_card_coupon.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card_coupon.car_owner_id
     *
     * @return the value of t_card_coupon.car_owner_id
     *
     * @mbg.generated
     */
    public Integer getCarOwnerId() {
        return carOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card_coupon.car_owner_id
     *
     * @param carOwnerId the value for t_card_coupon.car_owner_id
     *
     * @mbg.generated
     */
    public void setCarOwnerId(Integer carOwnerId) {
        this.carOwnerId = carOwnerId;
    }
}