package com.produce.entity;

public class TJournalProcess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.process_id
     *
     * @mbg.generated
     */
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.process_name
     *
     * @mbg.generated
     */
    private String processName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.process_time
     *
     * @mbg.generated
     */
    private Integer processTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.car_plate
     *
     * @mbg.generated
     */
    private String carPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.request_msg
     *
     * @mbg.generated
     */
    private String requestMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.response_msg
     *
     * @mbg.generated
     */
    private String responseMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_process.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.id
     *
     * @return the value of t_journal_process.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.id
     *
     * @param id the value for t_journal_process.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.process_id
     *
     * @return the value of t_journal_process.process_id
     *
     * @mbg.generated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.process_id
     *
     * @param processId the value for t_journal_process.process_id
     *
     * @mbg.generated
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.process_name
     *
     * @return the value of t_journal_process.process_name
     *
     * @mbg.generated
     */
    public String getProcessName() {
        return processName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.process_name
     *
     * @param processName the value for t_journal_process.process_name
     *
     * @mbg.generated
     */
    public void setProcessName(String processName) {
        this.processName = processName == null ? null : processName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.process_time
     *
     * @return the value of t_journal_process.process_time
     *
     * @mbg.generated
     */
    public Integer getProcessTime() {
        return processTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.process_time
     *
     * @param processTime the value for t_journal_process.process_time
     *
     * @mbg.generated
     */
    public void setProcessTime(Integer processTime) {
        this.processTime = processTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.park_id
     *
     * @return the value of t_journal_process.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.park_id
     *
     * @param parkId the value for t_journal_process.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.order_id
     *
     * @return the value of t_journal_process.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.order_id
     *
     * @param orderId the value for t_journal_process.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.car_plate
     *
     * @return the value of t_journal_process.car_plate
     *
     * @mbg.generated
     */
    public String getCarPlate() {
        return carPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.car_plate
     *
     * @param carPlate the value for t_journal_process.car_plate
     *
     * @mbg.generated
     */
    public void setCarPlate(String carPlate) {
        this.carPlate = carPlate == null ? null : carPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.project_name
     *
     * @return the value of t_journal_process.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.project_name
     *
     * @param projectName the value for t_journal_process.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.request_msg
     *
     * @return the value of t_journal_process.request_msg
     *
     * @mbg.generated
     */
    public String getRequestMsg() {
        return requestMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.request_msg
     *
     * @param requestMsg the value for t_journal_process.request_msg
     *
     * @mbg.generated
     */
    public void setRequestMsg(String requestMsg) {
        this.requestMsg = requestMsg == null ? null : requestMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.response_msg
     *
     * @return the value of t_journal_process.response_msg
     *
     * @mbg.generated
     */
    public String getResponseMsg() {
        return responseMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.response_msg
     *
     * @param responseMsg the value for t_journal_process.response_msg
     *
     * @mbg.generated
     */
    public void setResponseMsg(String responseMsg) {
        this.responseMsg = responseMsg == null ? null : responseMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_process.create_time
     *
     * @return the value of t_journal_process.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_process.create_time
     *
     * @param createTime the value for t_journal_process.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}