package com.produce.entity;

public class TNotice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.n_area
     *
     * @mbg.generated
     */
    private String nArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.n_type
     *
     * @mbg.generated
     */
    private Integer nType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.begin_time
     *
     * @mbg.generated
     */
    private String beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.end_time
     *
     * @mbg.generated
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.n_content
     *
     * @mbg.generated
     */
    private String nContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.n_link
     *
     * @mbg.generated
     */
    private String nLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.id
     *
     * @return the value of t_notice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.id
     *
     * @param id the value for t_notice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.n_area
     *
     * @return the value of t_notice.n_area
     *
     * @mbg.generated
     */
    public String getnArea() {
        return nArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.n_area
     *
     * @param nArea the value for t_notice.n_area
     *
     * @mbg.generated
     */
    public void setnArea(String nArea) {
        this.nArea = nArea == null ? null : nArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.n_type
     *
     * @return the value of t_notice.n_type
     *
     * @mbg.generated
     */
    public Integer getnType() {
        return nType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.n_type
     *
     * @param nType the value for t_notice.n_type
     *
     * @mbg.generated
     */
    public void setnType(Integer nType) {
        this.nType = nType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.begin_time
     *
     * @return the value of t_notice.begin_time
     *
     * @mbg.generated
     */
    public String getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.begin_time
     *
     * @param beginTime the value for t_notice.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime == null ? null : beginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.end_time
     *
     * @return the value of t_notice.end_time
     *
     * @mbg.generated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.end_time
     *
     * @param endTime the value for t_notice.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.n_content
     *
     * @return the value of t_notice.n_content
     *
     * @mbg.generated
     */
    public String getnContent() {
        return nContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.n_content
     *
     * @param nContent the value for t_notice.n_content
     *
     * @mbg.generated
     */
    public void setnContent(String nContent) {
        this.nContent = nContent == null ? null : nContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.n_link
     *
     * @return the value of t_notice.n_link
     *
     * @mbg.generated
     */
    public String getnLink() {
        return nLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.n_link
     *
     * @param nLink the value for t_notice.n_link
     *
     * @mbg.generated
     */
    public void setnLink(String nLink) {
        this.nLink = nLink == null ? null : nLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.status
     *
     * @return the value of t_notice.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.status
     *
     * @param status the value for t_notice.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.create_person
     *
     * @return the value of t_notice.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.create_person
     *
     * @param createPerson the value for t_notice.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.create_time
     *
     * @return the value of t_notice.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.create_time
     *
     * @param createTime the value for t_notice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}