package com.produce.entity;

public class TParkCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.car_plate
     *
     * @mbg.generated
     */
    private String carPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.car_owner_id
     *
     * @mbg.generated
     */
    private Integer carOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.begin_date
     *
     * @mbg.generated
     */
    private String beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.end_date
     *
     * @mbg.generated
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.parking_space
     *
     * @mbg.generated
     */
    private Integer parkingSpace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.is_enable
     *
     * @mbg.generated
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_car.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.id
     *
     * @return the value of t_park_car.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.id
     *
     * @param id the value for t_park_car.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.car_plate
     *
     * @return the value of t_park_car.car_plate
     *
     * @mbg.generated
     */
    public String getCarPlate() {
        return carPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.car_plate
     *
     * @param carPlate the value for t_park_car.car_plate
     *
     * @mbg.generated
     */
    public void setCarPlate(String carPlate) {
        this.carPlate = carPlate == null ? null : carPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.car_owner_id
     *
     * @return the value of t_park_car.car_owner_id
     *
     * @mbg.generated
     */
    public Integer getCarOwnerId() {
        return carOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.car_owner_id
     *
     * @param carOwnerId the value for t_park_car.car_owner_id
     *
     * @mbg.generated
     */
    public void setCarOwnerId(Integer carOwnerId) {
        this.carOwnerId = carOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.park_id
     *
     * @return the value of t_park_car.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.park_id
     *
     * @param parkId the value for t_park_car.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.begin_date
     *
     * @return the value of t_park_car.begin_date
     *
     * @mbg.generated
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.begin_date
     *
     * @param beginDate the value for t_park_car.begin_date
     *
     * @mbg.generated
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate == null ? null : beginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.end_date
     *
     * @return the value of t_park_car.end_date
     *
     * @mbg.generated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.end_date
     *
     * @param endDate the value for t_park_car.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.parking_space
     *
     * @return the value of t_park_car.parking_space
     *
     * @mbg.generated
     */
    public Integer getParkingSpace() {
        return parkingSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.parking_space
     *
     * @param parkingSpace the value for t_park_car.parking_space
     *
     * @mbg.generated
     */
    public void setParkingSpace(Integer parkingSpace) {
        this.parkingSpace = parkingSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.is_enable
     *
     * @return the value of t_park_car.is_enable
     *
     * @mbg.generated
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.is_enable
     *
     * @param isEnable the value for t_park_car.is_enable
     *
     * @mbg.generated
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_car.update_time
     *
     * @return the value of t_park_car.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_car.update_time
     *
     * @param updateTime the value for t_park_car.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}