package com.produce.entity;

public class TPaySequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sequence.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sequence.car_owner_id
     *
     * @mbg.generated
     */
    private Integer carOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sequence.pay_type_id
     *
     * @mbg.generated
     */
    private Integer payTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_sequence.sequence
     *
     * @mbg.generated
     */
    private Integer sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sequence.id
     *
     * @return the value of t_pay_sequence.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sequence.id
     *
     * @param id the value for t_pay_sequence.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sequence.car_owner_id
     *
     * @return the value of t_pay_sequence.car_owner_id
     *
     * @mbg.generated
     */
    public Integer getCarOwnerId() {
        return carOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sequence.car_owner_id
     *
     * @param carOwnerId the value for t_pay_sequence.car_owner_id
     *
     * @mbg.generated
     */
    public void setCarOwnerId(Integer carOwnerId) {
        this.carOwnerId = carOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sequence.pay_type_id
     *
     * @return the value of t_pay_sequence.pay_type_id
     *
     * @mbg.generated
     */
    public Integer getPayTypeId() {
        return payTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sequence.pay_type_id
     *
     * @param payTypeId the value for t_pay_sequence.pay_type_id
     *
     * @mbg.generated
     */
    public void setPayTypeId(Integer payTypeId) {
        this.payTypeId = payTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_sequence.sequence
     *
     * @return the value of t_pay_sequence.sequence
     *
     * @mbg.generated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_sequence.sequence
     *
     * @param sequence the value for t_pay_sequence.sequence
     *
     * @mbg.generated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}