package com.produce.dao.sqlProvider;

import com.produce.entity.TCarRecord;
import com.produce.entity.TCarRecordCriteria.Criteria;
import com.produce.entity.TCarRecordCriteria.Criterion;
import com.produce.entity.TCarRecordCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TCarRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_record
     *
     * @mbg.generated
     */
    public String countByExample(TCarRecordCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_car_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_record
     *
     * @mbg.generated
     */
    public String deleteByExample(TCarRecordCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_car_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_record
     *
     * @mbg.generated
     */
    public String insertSelective(TCarRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_car_record");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getCarQuery() != null) {
            sql.VALUES("car_query", "#{carQuery,jdbcType=INTEGER}");
        }
        
        if (record.getCarId() != null) {
            sql.VALUES("car_id", "#{carId,jdbcType=INTEGER}");
        }
        
        if (record.getCarPlate() != null) {
            sql.VALUES("car_plate", "#{carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.VALUES("order_id", "#{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedPay() != null) {
            sql.VALUES("need_pay", "#{needPay,jdbcType=INTEGER}");
        }
        
        if (record.getActualPay() != null) {
            sql.VALUES("actual_pay", "#{actualPay,jdbcType=INTEGER}");
        }
        
        if (record.getBeforePay() != null) {
            sql.VALUES("before_pay", "#{beforePay,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPay() != null) {
            sql.VALUES("coupon_pay", "#{couponPay,jdbcType=INTEGER}");
        }
        
        if (record.getInTime() != null) {
            sql.VALUES("in_time", "#{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.VALUES("out_time", "#{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getInTimeQuery() != null) {
            sql.VALUES("in_time_query", "#{inTimeQuery,jdbcType=INTEGER}");
        }
        
        if (record.getOutTimeQuery() != null) {
            sql.VALUES("out_time_query", "#{outTimeQuery,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_record
     *
     * @mbg.generated
     */
    public String selectByExample(TCarRecordCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("car_query");
        sql.SELECT("car_id");
        sql.SELECT("car_plate");
        sql.SELECT("park_id");
        sql.SELECT("order_id");
        sql.SELECT("need_pay");
        sql.SELECT("actual_pay");
        sql.SELECT("before_pay");
        sql.SELECT("coupon_pay");
        sql.SELECT("in_time");
        sql.SELECT("out_time");
        sql.SELECT("in_time_query");
        sql.SELECT("out_time_query");
        sql.FROM("t_car_record");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_record
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TCarRecord record = (TCarRecord) parameter.get("record");
        TCarRecordCriteria example = (TCarRecordCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_car_record");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getCarQuery() != null) {
            sql.SET("car_query = #{record.carQuery,jdbcType=INTEGER}");
        }
        
        if (record.getCarId() != null) {
            sql.SET("car_id = #{record.carId,jdbcType=INTEGER}");
        }
        
        if (record.getCarPlate() != null) {
            sql.SET("car_plate = #{record.carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{record.orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedPay() != null) {
            sql.SET("need_pay = #{record.needPay,jdbcType=INTEGER}");
        }
        
        if (record.getActualPay() != null) {
            sql.SET("actual_pay = #{record.actualPay,jdbcType=INTEGER}");
        }
        
        if (record.getBeforePay() != null) {
            sql.SET("before_pay = #{record.beforePay,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPay() != null) {
            sql.SET("coupon_pay = #{record.couponPay,jdbcType=INTEGER}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getInTimeQuery() != null) {
            sql.SET("in_time_query = #{record.inTimeQuery,jdbcType=INTEGER}");
        }
        
        if (record.getOutTimeQuery() != null) {
            sql.SET("out_time_query = #{record.outTimeQuery,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_record
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_car_record");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("car_query = #{record.carQuery,jdbcType=INTEGER}");
        sql.SET("car_id = #{record.carId,jdbcType=INTEGER}");
        sql.SET("car_plate = #{record.carPlate,jdbcType=VARCHAR}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("order_id = #{record.orderId,jdbcType=VARCHAR}");
        sql.SET("need_pay = #{record.needPay,jdbcType=INTEGER}");
        sql.SET("actual_pay = #{record.actualPay,jdbcType=INTEGER}");
        sql.SET("before_pay = #{record.beforePay,jdbcType=INTEGER}");
        sql.SET("coupon_pay = #{record.couponPay,jdbcType=INTEGER}");
        sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        sql.SET("in_time_query = #{record.inTimeQuery,jdbcType=INTEGER}");
        sql.SET("out_time_query = #{record.outTimeQuery,jdbcType=INTEGER}");
        
        TCarRecordCriteria example = (TCarRecordCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_record
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TCarRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("t_car_record");
        
        if (record.getCarQuery() != null) {
            sql.SET("car_query = #{carQuery,jdbcType=INTEGER}");
        }
        
        if (record.getCarId() != null) {
            sql.SET("car_id = #{carId,jdbcType=INTEGER}");
        }
        
        if (record.getCarPlate() != null) {
            sql.SET("car_plate = #{carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getNeedPay() != null) {
            sql.SET("need_pay = #{needPay,jdbcType=INTEGER}");
        }
        
        if (record.getActualPay() != null) {
            sql.SET("actual_pay = #{actualPay,jdbcType=INTEGER}");
        }
        
        if (record.getBeforePay() != null) {
            sql.SET("before_pay = #{beforePay,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPay() != null) {
            sql.SET("coupon_pay = #{couponPay,jdbcType=INTEGER}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getInTimeQuery() != null) {
            sql.SET("in_time_query = #{inTimeQuery,jdbcType=INTEGER}");
        }
        
        if (record.getOutTimeQuery() != null) {
            sql.SET("out_time_query = #{outTimeQuery,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_record
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TCarRecordCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}