package com.produce.dao.sqlProvider;

import com.produce.entity.TJournalProcess;
import com.produce.entity.TJournalProcessCriteria.Criteria;
import com.produce.entity.TJournalProcessCriteria.Criterion;
import com.produce.entity.TJournalProcessCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TJournalProcessSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_process
     *
     * @mbg.generated
     */
    public String countByExample(TJournalProcessCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_journal_process");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_process
     *
     * @mbg.generated
     */
    public String deleteByExample(TJournalProcessCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_journal_process");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_process
     *
     * @mbg.generated
     */
    public String insertSelective(TJournalProcess record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_journal_process");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getProcessId() != null) {
            sql.VALUES("process_id", "#{processId,jdbcType=VARCHAR}");
        }
        
        if (record.getProcessName() != null) {
            sql.VALUES("process_name", "#{processName,jdbcType=VARCHAR}");
        }
        
        if (record.getProcessTime() != null) {
            sql.VALUES("process_time", "#{processTime,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.VALUES("order_id", "#{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlate() != null) {
            sql.VALUES("car_plate", "#{carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getProjectName() != null) {
            sql.VALUES("project_name", "#{projectName,jdbcType=VARCHAR}");
        }
        
        if (record.getRequestMsg() != null) {
            sql.VALUES("request_msg", "#{requestMsg,jdbcType=VARCHAR}");
        }
        
        if (record.getResponseMsg() != null) {
            sql.VALUES("response_msg", "#{responseMsg,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_process
     *
     * @mbg.generated
     */
    public String selectByExample(TJournalProcessCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("process_id");
        sql.SELECT("process_name");
        sql.SELECT("process_time");
        sql.SELECT("park_id");
        sql.SELECT("order_id");
        sql.SELECT("car_plate");
        sql.SELECT("project_name");
        sql.SELECT("request_msg");
        sql.SELECT("response_msg");
        sql.SELECT("create_time");
        sql.FROM("t_journal_process");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_process
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TJournalProcess record = (TJournalProcess) parameter.get("record");
        TJournalProcessCriteria example = (TJournalProcessCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_journal_process");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getProcessId() != null) {
            sql.SET("process_id = #{record.processId,jdbcType=VARCHAR}");
        }
        
        if (record.getProcessName() != null) {
            sql.SET("process_name = #{record.processName,jdbcType=VARCHAR}");
        }
        
        if (record.getProcessTime() != null) {
            sql.SET("process_time = #{record.processTime,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{record.orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlate() != null) {
            sql.SET("car_plate = #{record.carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getProjectName() != null) {
            sql.SET("project_name = #{record.projectName,jdbcType=VARCHAR}");
        }
        
        if (record.getRequestMsg() != null) {
            sql.SET("request_msg = #{record.requestMsg,jdbcType=VARCHAR}");
        }
        
        if (record.getResponseMsg() != null) {
            sql.SET("response_msg = #{record.responseMsg,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_process
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_journal_process");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("process_id = #{record.processId,jdbcType=VARCHAR}");
        sql.SET("process_name = #{record.processName,jdbcType=VARCHAR}");
        sql.SET("process_time = #{record.processTime,jdbcType=INTEGER}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("order_id = #{record.orderId,jdbcType=VARCHAR}");
        sql.SET("car_plate = #{record.carPlate,jdbcType=VARCHAR}");
        sql.SET("project_name = #{record.projectName,jdbcType=VARCHAR}");
        sql.SET("request_msg = #{record.requestMsg,jdbcType=VARCHAR}");
        sql.SET("response_msg = #{record.responseMsg,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=VARCHAR}");
        
        TJournalProcessCriteria example = (TJournalProcessCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_process
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TJournalProcess record) {
        SQL sql = new SQL();
        sql.UPDATE("t_journal_process");
        
        if (record.getProcessId() != null) {
            sql.SET("process_id = #{processId,jdbcType=VARCHAR}");
        }
        
        if (record.getProcessName() != null) {
            sql.SET("process_name = #{processName,jdbcType=VARCHAR}");
        }
        
        if (record.getProcessTime() != null) {
            sql.SET("process_time = #{processTime,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getCarPlate() != null) {
            sql.SET("car_plate = #{carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getProjectName() != null) {
            sql.SET("project_name = #{projectName,jdbcType=VARCHAR}");
        }
        
        if (record.getRequestMsg() != null) {
            sql.SET("request_msg = #{requestMsg,jdbcType=VARCHAR}");
        }
        
        if (record.getResponseMsg() != null) {
            sql.SET("response_msg = #{responseMsg,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_process
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TJournalProcessCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}